name: Publish Docker image

on:
  push:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (including latest tag)
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Build and push (excluding latest tag)
        uses: docker/build-push-action@v5
        if : github.ref != 'refs/heads/main'
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
